name: Deploy Bot to Server and start

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      TELEGRAM_BOT_KEY: ${{ secrets.TELEGRAM_BOT_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: runner

      - name: Pull latest changes on the server
        run: |
          cd runner
          git fetch origin
          git reset --hard origin/master

      - name: Install dependencies
        run: |
          cd runner
          npm install
          nvm use 22.7.0

      - name: Set environment variables
        run: |
          cd runner
          echo "TELEGRAM_BOT_KEY=${{ secrets.TELEGRAM_BOT_KEY }}" >> .env

      - name: Kill existing bot process
        run: |
          pm2 delete bot || true

      - name: Start Telegram bot
        run: |
          cd runner
          pm2 start index.js --name bot
          # Check if the bot is running
          pm2 status bot

      - name: Verify if the bot is running
        run: |
          pm2 status bot || (echo "Bot failed to start" && exit 1)
          echo "Bot is running successfully"

      - name: Check logs for any errors
        run: |
          pm2 logs bot --lines 100